### PR TITLE
Add data-binding for yAxis

### PR DESCRIPTION
**Pull request by sorin-davidoi**
Decided to remove the previous value for yAxis. However, this could remain and be extended by the user-supplied object.

### CODE REVIEW

**Comment by avdaredevil** [comment]
Any reason for this? What problem were you running into with this design?

**Comment by sorin-davidoi** [comment]
Maybe I'm missing something. I was trying to add a custom formatter for the Y axis, something like:
```javascript
yAxis: { type: Object, value: {
          title: { text: null },
          gridLineWidth: 0,
          tickInterval: 25,
          maxPadding: 0,
          labels: { formatter: formatYAxisLabel }
        }},
```

**Comment by avdaredevil** [comment]
The API provided for this is:
```javascript
app.$.myChart._chart.yAxis[0].update({
    type: Object,
    value: {
          title: {text: null},
          gridLineWidth: 0,
          tickInterval: 25,
          maxPadding: 0,
          labels: {formatter: formatYAxisLabel}
    }
})
```

**Comment by sorin-davidoi** [comment]
Thanks for the example. That works, but I feel that is exhibits a few drawbacks:
 - accessing the underlying implementation is kind of a hack; the purpose of the web-component should be to hide the actual implementation

- the overhead of setting up an observer and calling `update` again if I want to change one of the properties

- taking extra care to check that app.$.myChart is defined (in my case, it is inside a `dom-if` template)

- inconsistency with the `x-axis` API

**Comment by avdaredevil** [comment]
Good points. Merging.

**Pull request merged**
