### PR TITLE
Add support for highchart 3D.

### PR DESCRIPTION
**Pull request by dariemp**
Add support for 3D charts.

### CODE REVIEW

**Comment by avdaredevil** [comment]
Could you isolate 3d properties to a behavior and add observers for binding?

**Comment by dariemp** [comment]
Hi. Do you mean have a different behavior for the 3d properties, different than ChartBehavior? About the observers: sure, no problem.

**Comment by avdaredevil** [comment]
Yup precisely. It seems impractical to include the 3D Library within the normal distribution. For three-dimensional charts they should have their own custom component. This way highcharts-3D can be built as its own component implementing both  aforementioned behaviors and only importing to 3D Library when necessary.

Thoughts?

**Comment by avdaredevil** [comment]
Any updates @dariemp?

**Pull request closed without merging**
